# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
    - flake8-docstrings
    - flake8-eradicate
    - flake8-executable
    - flake8-logging-format
    - flake8-mutable
    - flake8-print
    - flake8-return
    - flake8-self
    - pep8-naming
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: requirements-txt-fixer
  - id: check-merge-conflict
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: debug-statements
- repo: https://github.com/adrienverge/yamllint
  rev: v1.28.0
  hooks:
  - id: yamllint
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0-alpha.4
  hooks:
  - id: prettier
    types_or: [css, javascript]
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.5.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
    - mdformat-shfmt
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v8.29.0
  hooks:
  - id: eslint
    args: [--format=compact]
    additional_dependencies:
    - prettier@1.0
    - eslint@8.29.0
    - eslint-plugin-import@2.18.0
    - eslint-plugin-node@11.1.0
    - eslint-plugin-promise@4.2.1
    - eslint-plugin-standard@4.0.0
    - eslint-config-prettier@1.0
    - eslint-plugin-prettier@1.0
- repo: https://github.com/awebdeveloper/pre-commit-stylelint
  rev: 0.0.2
  hooks:
  - id: stylelint
    args: [--formatter=compact]
    additional_dependencies:
    - stylelint@1.0
    - stylelint-config-prettier@1.0
    - stylelint-prettier@1.0
    - prettier@1.0
exclude: ^.github/ISSUE_TEMPLATE/snippets/.*$
