#!/bin/sh

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

#git grep -l 'Copyright .*[0-9][ –-]\+\(201[0-9]\|202[0123]\) Michal Čihař' | grep -v '\.po$' | xargs -r sed -i 's/\(Copyright [^0-9]*\)\([0-9]\+[ –-]\+[0-9]\+\) \(Michal Čihař\) <michal@[^>]\+>/\1\3 <michal@weblate.org>/'

#sed -i s@https://github.com/charliermarsh/ruff-pre-commit@https://github.com/astral-sh/ruff-pre-commit@ .pre-commit-config.yaml

for file in .github/workflows/*.yml ; do
    "${ROOT:-.}/update-workflow" "$file"
done

"${ROOT:-.}/update-pre-commit" .pre-commit-config.yaml

if [ -f pyproject.toml ] ; then
    sed -i '/output-format = "github"/D' pyproject.toml
    pre-commit run --files pyproject.toml || true
fi

sed -i 's,uses: codecov/codecov-action.*,uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0,' .github/workflows/*
sed -i 's,uses: astral-sh/setup-uv.*,uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f0640537287 # v5.3.0,' .github/workflows/*
sed -i 's,uses: actions/stale.*,uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9.1.0,' .github/workflows/*
sed -i 's,uses: actions/checkout.*,uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2,' .github/workflows/*
sed -i 's,uses: actions/setup-python.*,uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0,' .github/workflows/*
sed -i 's,uses: peter-evans/create-or-update-comment.*,uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0,' .github/workflows/*
sed -i 's,uses: actions/cache.*,uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1,' .github/workflows/*
sed -i 's,uses: peter-evans/create-pull-request.*,uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7.0.7,' .github/workflows/*
sed -i 's,uses: srealmoreno/label-sync-action.*,uses: srealmoreno/label-sync-action@850ba5cef2b25e56c6c420c4feed0319294682fd # v2.0.0,' .github/workflows/*
sed -i 's,uses: stefanzweifel/git-auto-commit-action.*,uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0,' .github/workflows/*
sed -i 's,uses: actions/upload-artifact.*,uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4.6.1,' .github/workflows/*

sed -i 's,uses: actions/download-artifact.*,uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9,' .github/workflows/*

sed -i 's,uses: actions/attest-build-provenance.*,uses: actions/attest-build-provenance@f9eaf234fc1c2e333c1eca18177db0f44fa6ba52 # v2.2.1,' .github/workflows/*

sed -i 's,uses: ncipollo/release-action.*,uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0,' .github/workflows/*

sed -i 's,uses: codecov/test-results-action.*,uses: codecov/test-results-action@5c441a7bcc06f8706cde90192857d337c5dab8a6 # v1.0.4,' .github/workflows/*

sed -i 's,uses: github/codeql-action/upload-sarif.*,uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3.28.10,' .github/workflows/*

sed -i 's,uses: EnricoMi/publish-unit-test-result-action.*,uses: EnricoMi/publish-unit-test-result-action@170bf24d20d201b842d7a52403b73ed297e6645b # v2.18.0,' .github/workflows/*

sed -i 's,uses: tj-actions/changed-files.*,uses: tj-actions/changed-files@dcc7a0cba800f454d79fff4b993e8c3555bcc0a8 # v45.0.7,' .github/workflows/*

sed -i 's,uses: anchore/scan-action.*,uses: anchore/scan-action@7c05671ae9be166aeb155bad2d7df9121823df32 # v6.1.0,' .github/workflows/*

sed -i 's,uses: aquasecurity/trivy-action.*,uses: aquasecurity/trivy-action@18f2510ee396bbf400402947b394f2dd8c87dbb0 # 0.29.0,' .github/workflows/*

sed -i 's,uses: crazy-max/ghaction-github-runtime.*,uses: crazy-max/ghaction-github-runtime@b3a9207c0e1ef41f4cf215303c976869d0c2c1c4 # v3.0.0,' .github/workflows/*

sed -i 's,uses: docker/login-action.*,uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0,' .github/workflows/*

sed -i 's,uses: docker/setup-buildx-action.*,uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0,' .github/workflows/*

sed -i 's,uses: github/codeql-action/upload-sarif.*,uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # v3.28.10,' .github/workflows/*

sed -i 's,uses: peter-evans/dockerhub-description.*,uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0,' .github/workflows/*


sed -i 's,uses: actions/github-script.*,uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1,' .github/workflows/*

sed -i 's,uses: azure/setup-helm.*,uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v4.3.0,' .github/workflows/*

sed -i 's,uses: docker/build-push-action.*,uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0,' .github/workflows/*

sed -i 's,uses: docker/metadata-action.*,uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0,' .github/workflows/*

sed -i 's,uses: docker/setup-qemu-action.*,uses: docker/setup-qemu-action@5964de0df58d5ad28b04d8fe2e6b80ad47105b91 # v3.5.0,' .github/workflows/*
