#!/bin/bash

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

sed -i '/# renovate: datasource=pypi depName=uv /D' .github/workflows/*.{yml,yaml}

if [ -f pyproject.toml ]; then
    sed -i 's/pre-commit==[0-9.]+/prek==0.3.1/' pyproject.toml
fi

if [ -f requirements.txt ] || [ -f requirements-lint.txt ]; then
    sed -i 's/pre-commit==[0-9.]+/prek==0.3.1/' requirements*.txt
fi

for file in .github/workflows/*.{yml,yaml}; do
    "${ROOT:-.}/update-workflow" "$file"
done

"${ROOT:-.}/update-pre-commit" .pre-commit-config.yaml
