#!/bin/sh

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

if [ -f .github/workflows/ruff.yml ] && ! grep -q tool.ruff pyproject.toml ; then
    cat >> pyproject.toml <<EOT

[tool.ruff]
format = "github"
ignore = [
]
select = [
  "E",
  "F",
  "B",
  "T10",
  "A",
  "C4",
  "C90",
  "YTT",
  "DJ",
  "UP",
  "D",
  "PD",
  "PGH",
  "PL",
  "TRY",
  "RUF",
  "ERA",
  "ICN",
  "ISC",
  "EXE",
  "INP",
  "PIE",
  "G",
  "PYI",
  "Q",
  "SIM",
  "TID",
  "RSE",
  "T20",
  "RET",
  "SLF",
  "N"
]
target-version = "py37"

[tool.ruff.mccabe]
max-complexity = 16
EOT
fi

#git grep -l 'Copyright .*[0-9][ –-]\+\(201[0-9]\|202[0123]\) Michal Čihař' | grep -v '\.po$' | xargs -r sed -i 's/\(Copyright [^0-9]*\)\([0-9]\+[ –-]\+[0-9]\+\) \(Michal Čihař\) <michal@[^>]\+>/\1\3 <michal@weblate.org>/'
