#!/usr/bin/env python3

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

"""Synchronizes GitHub workflows for Weblate repositories."""

import subprocess
import sys

import ruamel.yaml

RUNS_UPDATE = {
    "ubuntu-latest": "ubuntu-24.04",
    "macos-latest": "macos-14",
    "windows-latest": "windows-2022",
}

yaml = ruamel.yaml.YAML()
yaml.indent = 2
yaml.preserve_quotes = False
yaml.width = sys.maxsize

with open(sys.argv[1]) as handle:
    data = yaml.load(handle)

modified = False

if "permissions" not in data:
    data["permissions"] = {"contents": "read"}
    modified = True

for job_name in data["jobs"]:
    job = data["jobs"][job_name]

    # Avoid using *-latest OS, pin it instead
    if "runs-on" in job and job["runs-on"] in RUNS_UPDATE:
        job["runs-on"] = RUNS_UPDATE[job["runs-on"]]
        modified = True

    if "steps" in job:
        for step in job["steps"]:
            uses = step.get("uses", "")
            if uses.startswith("actions/checkout@"):
                if "with" not in step:
                    step["with"] = {}
                if "persist-credentials" not in step["with"]:
                    step["with"]["persist-credentials"] = "token" in step["with"]
                    modified = True
            if uses.startswith("astral-sh/setup-uv@"):
                if "with" not in step:
                    step["with"] = ruamel.yaml.CommentedMap()
                if "version" not in step["with"]:
                    step["with"]["version"] = "0.9.4"
                    step["with"].yaml_set_comment_before_after_key(
                        key="version",
                        before="renovate: datasource=pypi depName=uv versioning=pep440",
                        indent=8,
                    )
                    modified = True

if modified:
    with open(sys.argv[1], "w") as handle:
        yaml.dump(data, handle)

    subprocess.run(
        ["pre-commit", "run", "--files", sys.argv[1]], check=False, capture_output=True
    )
