#!/usr/bin/env python
"""Generate issue templates from snippets."""

FILES = {
    "bug_report.yml": (
        "head",
        "bug_report",
        "intro",
        "describe-issue",
        "tried",
        "reproduce",
        "expected",
        "screenshots",
        "exception",
        "additional",
    ),
    "bug_report.yml.weblate": (
        "head",
        "bug_report",
        "intro",
        "describe-issue",
        "tried",
        "reproduce",
        "expected",
        "screenshots",
        "exception",
        "weblate-versions",
        "weblate-checks",
        "additional",
    ),
    "feature_request.yml": (
        "head",
        "feature_request",
        "intro",
        "feature-describe",
        "feature-solution",
        "feature-alternatives",
        "screenshots",
        "additional",
    ),
    "support_question.yml": (
        "head",
        "support_question",
        "intro",
        "commercial",
        "describe-issue",
        "tried",
        "reproduce",
        "expected",
        "screenshots",
        "exception",
        "additional",
    ),
    "support_question.yml.weblate": (
        "head",
        "support_question",
        "intro",
        "commercial",
        "describe-issue",
        "tried",
        "reproduce",
        "expected",
        "screenshots",
        "exception",
        "weblate-versions",
        "weblate-checks",
        "additional",
    ),
}

SNIPPETS = {}
for snippets in FILES.values():
    for snippet in snippets:
        if snippet not in SNIPPETS:
            filename = f".github/ISSUE_TEMPLATE/snippets/{snippet}.yml"
            with open(filename, "r") as handle:
                SNIPPETS[snippet] = handle.read()

for filename, snippets in FILES.items():
    with open(f".github/ISSUE_TEMPLATE/{filename}", "w") as handle:
        for snippet in snippets:
            handle.write(SNIPPETS[snippet])
