contact_links:
  - name: Get Professional Support
    url: https://weblate.org/support/
    about: As the subscriber, you will always receive fast replies from our dedicated support team.
  - name: Ask a Question
    url: https://github.com/WeblateOrg/weblate/discussions
    about: Want to discuss something with a community? Use our discussions!
  - name: Read the Docs
    url: https://docs.weblate.org/
    about: Be sure you've read the docs!
