contact_links:
  - name: Paid support
    url: https://weblate.org/support/
    about: As the subscriber, you will always receive fast replies from our dedicated support team.
  - name: Community discussions
    url: https://github.com/WeblateOrg/weblate/discussions
    about: Want to discuss something with a community? Use our discussions!
