name: Bug report
description: Create a report to help us improve
body:
- type: markdown
  attributes:
    value: |
      Thank you for reporting an issue.
      This form guides you in creating a useful issue report.
