- type: textarea
  id: what-happened
  attributes:
    label: Describe the issue
    description: >
      A clear and concise description of the problem you are facing.

      Please include important information, like the file format you are using and installed add-ons.
    placeholder: Tell us what you see!
  validations:
    required: true
