- type: textarea
  id: traceback
  attributes:
    label: Exception traceback
    description: >
      In case you observed a server error or crash, please read
      [the debugging documentation](https://docs.weblate.org/en/latest/contributing/debugging.html)
      for information on obtaining the relevant logs.

      This field will be rendered as a Python traceback automatically.
    render: pytb
