- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: A clear and concise description of what you expected to happen.
    placeholder: Tell us what you want to see!
