- type: textarea
  id: describe
  attributes:
    label: Describe the problem
    description: >
      Is your feature request related to a problem? If so, please provide
      a clear and concise description of what the problem is.
      Ex. I'm always frustrated when [...]
  validations:
    required: true
