- type: textarea
  id: solution
  attributes:
    label: Describe the solution you would like
    description: A clear and concise description of what the new feature should do.
    placeholder: I'd like to get…
  validations:
    required: true
