- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
    placeholder: The issue can also be addressed by…
