- type: textarea
  id: solution
  attributes:
    label: Solution brainstorm
    description: We know you have ideas how to address this, please share it.
    placeholder: I'd like to get…
  validations:
    required: true
