- type: textarea
  id: alternatives
  attributes:
    label: Describe alternatives you have considered
    description: A clear and concise description of any alternative solutions or features you have considered.
    placeholder: The issue can also be addressed by…
