- type: textarea
  id: reproducer
  attributes:
    label: Steps to reproduce the behavior
    description: What did you do before the problem appeared?
    placeholder: |
      1. Go to '…'
      2. Scroll down to '…'
      3. Click on '…'
      4. The error occurs
  validations:
    required: true
