  - type: textarea
    id: checks
    attributes:
      label: Weblate deploy checks
      description: >
        Please paste the output of check --deploy command over here. Depending on
        the installation, these can be executed in a different way. Please consult
        https://docs.weblate.org/en/latest/admin/management.html for more details.

        On pip installed Weblate:

        ```
        weblate check --deploy
        ```

        On Git checkout:

        ```
        ./manage.py check --deploy
        ```

        Using docker-compose:

        ```
        docker-compose exec --user weblate weblate weblate check --deploy
        ```
      render: shell
