- type: dropdown
  id: installation
  attributes:
    label: How do you run Weblate?
    options:
    - ''
    - Docker container
    - weblate.org service
    - PyPI module
    - Git checkout
    - Other
  validations:
    required: true
- type: input
  id: version
  validations:
    required: true
  attributes:
    label: Weblate version
    description: What Weblate version do you use? You can usually figure this out at /about/ URL.
