# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Repository linting

on:
  schedule:
  - cron: 30 1 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-slim

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Use HTTPS for repository access
      run: 'git config --global url.https://github.com/.insteadOf git@github.com:'
    - name: Lint repositories
      run: ./lint.sh
